name: CD (Zip Deploy to Azure Web App - Windows)

on:
  workflow_run:
    workflows: ["CI DevSecOps Pipeline"]
    types: [completed]
    branches: [master]


permissions:
  contents: read
  actions: read

jobs:
  deploy-zip:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build & Publish (Release)
        run: dotnet publish NotesSampleApplication/NotesSampleApplication.csproj -c Release -o ./publish

      - name: Create deploy zip
        run: |
          cd publish
          zip -r ../app.zip .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}   # e.g., rawsolutions
          package: app.zip

      - name: Restart Web App
        run: |
          az webapp restart \
            --resource-group ${{ secrets.AZ_RG }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }}

      - name: Post-deploy health check
        run: |
          echo "🔍 Checking ${{
            secrets.PROD_URL
          }}/health ..."
          for i in {1..30}; do
            if curl -sf "${{ secrets.PROD_URL }}/health"; then
              echo "✅ Health check passed"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 5
          done
          echo "❌ App failed health check" && exit 1
