name: CD (Deploy to Azure on Windows)

on:
  workflow_run:
    workflows: ["CI DevSecOps Pipeline"] # must exactly match your CI 'name'
    types: [completed]
    branches: [master]

jobs:
  deploy-to-azure:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact from CI run
        uses: actions/download-artifact@v4
        with:
          name: notes-webapp-image
          path: ./notes-webapp-image
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify artifact contents
        run: |
          echo "📦 Listing artifact files:"
          ls -R ./notes-webapp-image

      - name: Load Docker image
        run: docker load -i ./notes-webapp-image/notes_web_app.tar

      - name: Tag Docker image for release
        run: docker tag notes_web_app:latest notes_web_app:release

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # e.g., rawsolution
          images: notes_web_app:release

      - name: Restart Web App
        run: |
          az webapp restart \
            --resource-group ${{ secrets.AZ_RG }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }}

      - name: Post-deploy health check
        run: |
          echo "🔍 Checking /health endpoint..."
          for i in {1..30}; do
            if curl -sf ${{ secrets.PROD_URL }}/health; then
              echo "✅ Health check passed"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 5
          done
          echo "❌ App failed health check" && exit 1
