name: CD (Deploy Docker Artifact to Azure)

on:
  workflow_run:
    workflows: ["CI DevSecOps Pipeline"]
    types: [completed]
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read   # needed to download artifacts from another run

jobs:
  deploy-to-azure:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Download artifact from the triggering CI run (only when fired by workflow_run)
      - name: Download Docker image artifact from CI run
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: "CI DevSecOps Pipeline"
          run_id: ${{ github.event.workflow_run.id }}
          name: notes-webapp-image
          path: ./image

      - name: Load Docker image
        run: docker load -i ./image/notes_web_app.tar

      - name: Tag Docker image for Azure
        run: docker tag notes_web_app:latest notes_web_app:release

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.rawsolutions }}
          images: notes_web_app:release

      - name: Restart Web App
        run: |
          az webapp restart \
            --name ${{ secrets.rawsolutions }} \
            --resource-group ${{ secrets.rawsolutions_group }}

      - name: Health Check
        run: |
          for i in {1..30}; do
            if curl -sf ${{ secrets.rawsolutions-h6bkfhb7c3htcxhw.newzealandnorth-01.azurewebsites.net }}/health; then
