name: CD - Deploy to Azure Container Apps

on:
  # Trigger when the CI workflow completes
  workflow_run:
    workflows: ["CI DevSecOps Pipeline"]  # CHANGE to your CI workflow name
    branches: [master]   #  CHANGE if you use a different default branch
    types:
      - completed

  # Allow manual deployment from Actions tab
  workflow_dispatch: 

env:
  #  UPDATE THESE VALUES:
  CONTAINER_APP_NAME: rawsolutions-web               # Must match your Container App name
  RESOURCE_GROUP: rawsolutions-production-rg         # Must match your Resource Group name
  IMAGE_NAME: ghcr.io/willmark12544/notes-web-app # e.g., ghcr.io/johnsmith/myapp

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Only run if CI succeeded OR if manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.IMAGE_NAME }}:latest

      

      - name: Get deployment URL
        run: |
          echo "::notice:: Deployment complete!"
          APP_URL=$(az containerapp show \
            --name "${{ env.CONTAINER_APP_NAME }}" \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --query "properties.configuration.ingress.fqdn" \
            --output tsv)
          echo "::notice:: Application URL: https://$APP_URL"

      - name: Azure logout
        if: always()
        run: az logout
