name: CD (Deploy Docker Artifact to Azure)

on:
  workflow_run:
    workflows: ["CI DevSecOps Pipeline"]   # must match the CI workflow name exactly
    types: [completed]
    branches: [master]
  workflow_dispatch: {}                     # allows manual trigger

jobs:
  deploy-to-azure:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ Download the Docker image artifact produced by CI
      - name: Download Docker image artifact
        uses: actions/download-artifact@v5
        with:
          name: notes-webapp-image
          path: ./image

      # 2️⃣ Load the Docker image
      - name: Load Docker image
        run: docker load -i ./image/notes_web_app.tar

      # 3️⃣ Tag image for Azure deployment
      - name: Tag Docker image
        run: docker tag notes_web_app:latest notes_web_app:release

      # 4️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5️⃣ Deploy container directly to Azure App Service
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.rawsolutions }}
          images: notes_web_app:release

      # 6️⃣ Restart web app
      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name ${{ secrets.rawsolutions }} \
            --resource-group ${{ secrets.rawsolutions_group }}

      # 7️⃣ Verify the deployment (health endpoint)
      - name: Health Check
        run: |
          for i in {1..30}; do
            if curl -sf ${{ secrets.rawsolutions-h6bkfhb7c3htcxhw.newzealandnorth-01.azurewebsites.net }}/health; then
              echo "✅ App is healthy!"
              exit 0
            fi
            echo "Waiting for app to become healthy..."
            sleep 5
          done
          echo "❌ App failed health check" && exit 1
